import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    company: "PT. Sangkuriang Internasional",
    logo: "/images/careers/sangkuriang-logo.webp",
    location: "Jakarta, Indonesia 🇮🇩",
    industry: "Technology / Software Development",
    link: "https://www.linkedin.com/company/sangkurianginternasional/",
    isShow: true,
    roles: [
      {
        position: "Backend Engineer",
        type: "Full-time",
        location_type: "Onsite",
        start_date: "2025-04",
        end_date: null,
        responsibilities: [
          "Developed Booking System using Golang microservices with internal service communication via gRPC, ensuring scalability and reliability.",
          "Integrated PowerPro Property Management System (PMS) for hotel operations, enabling real-time room availability, booking management, and guest data synchronization.",
          "Implemented Xendit payment gateway integration for secure online payment processing, supporting multiple payment methods and transaction management.",
          "Implemented authentication and authorization features with Firebase integration and Role-Based Access Control (RBAC) for secure user management.",
          "Designed and developed 8+ Golang microservices, contributing to the modularization and maintainability of the Sanur Integrated Platform.",
          "Supported frontend team (Next.js) by providing API integration, debugging, and feature improvements to ensure seamless user experience.",
          "Collaborated in agile development cycles, from requirement analysis, design, implementation, testing, to deployment.",
        ],
        projects: ["Sanur Integrated Platform"],
        tech_stack: ["Golang", "PostgreSQL", "gRPC", "Firebase", "Next.js", "PowerPro PMS API", "Xendit Payment Gateway"],
      },
      {
        position: "Fullstack Engineer",
        type: "Full-time",
        location_type: "Onsite",
        start_date: "2025-01",
        end_date: "2025-03",
        responsibilities: [
          "Designed and developed a Proof of Concept (POC) system for The Sanur project, delivering a functional prototype to validate business requirements and technical feasibility.",
          "Built backend microservices using Golang, implementing internal service communication via gRPC and external integrations via REST API and SOAP protocols.",
          "Developed frontend web application using Next.js, ensuring responsive UI/UX and seamless integration with backend services.",
          "Integrated with PostgreSQL database for reliable data persistence and query optimization.",
          "Collaborated closely with stakeholders and internal teams to iterate on requirements and deliver a successful POC within a short timeframe.",
        ],
        projects: ["POC The Sanur"],
        tech_stack: ["Golang", "Next.js", "PostgreSQL", "gRPC", "REST API", "SOAP"],
      },
      {
        position: "Backend Engineer",
        type: "Full-time",
        location_type: "Onsite",
        start_date: "2024-04",
        end_date: "2025-01",
        responsibilities: [
          "Maintained and enhanced Puskarda (Pusat Peradilan Pidana) system owned by Kominfo, focusing on bug fixing, performance optimization, and ensuring high system availability using Golang.",
          "Developed and maintained ETL pipelines for Puskarda using Python, enabling reliable extraction, transformation, and loading of judicial data into PostgreSQL databases.",
          "Built automation workflows in Node.js to streamline monthly data analysis, reducing manual processing time and improving reporting efficiency.",
          "Implemented monitoring solutions for system and application health using Grafana and Uptime Kuma, ensuring early detection of failures and improving system reliability.",
          "Collaborated with cross-functional teams (infrastructure & data teams) to support production deployment, troubleshoot critical issues, and optimize database queries.",
        ],
        projects: ["Puskarda", "ETL Puskarda", "Automation Puskarda"],
        tech_stack: ["Golang", "Python", "Node.js", "PostgreSQL", "Grafana", "Uptime Kuma"],
      },
    ],
  },
  {
    company: "PT. Ruang Raya Indonesia",
    logo: "/images/careers/ruangguru-logo.webp",
    location: "Jakarta, Indonesia 🇮🇩",
    industry: "Technology / EdTech",
    link: "https://www.linkedin.com/company/ruangraya/",
    isShow: true,
    roles: [
      {
        position: "Frontend Engineer",
        type: "Internship",
        location_type: "Remote",
        start_date: "2022-08",
        end_date: "2022-12",
        responsibilities: [
          "Built user interfaces using HTML, CSS, and JavaScript, implementing the React.js framework.",
          "Collaborated with the UI and Backend teams to ensure integration, and performed testing and debugging to ensure web functionality.",
          "Contributed to team discussions and meetings and served as an Assistant Mentor assigned to help interns complete their tasks and projects.",
        ],
        tech_stack: ["HTML", "CSS", "JavaScript", "React.js"],
      },
    ],
  },
];
